name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-17-jdk
          pip install cython buildozer
          buildozer init
          sed -i 's/#requirements = python3,kivy/requirements = python3,pygame/' buildozer.spec
          yes | buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
          
